# Default values for helm-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#deployment
Deployment_name: app-deployment
app_name: my-app
app_cont_port: 80
configMap: my-app-cm

#nodeport service
nodePort_name: my-app-np
type: NodePort
np_port: 8000
np_target: 8000
np_nodePort: 30080


#redis pod
redis_pod: redis-pod
containerPort: 6379
redis_img: gcr.io/mohamed-abdelrazik-project/redis_image
redis_cont_name: redis
redis_protocol: TCP
image:
  repository: gcr.io/mohamed-abdelrazik-project/python-app-img
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.






